from snakemake.utils import min_version

min_version("6.3.0")

configfile: "config/config.yaml"

include: "rules/common.smk"
include: "rules/trim.smk"
#include: "rules/QC.smk"
include: "rules/quant.smk"
include: "rules/sortmerna.smk"

rule all:
    input:
        #Kallisto output
        expand( "results/kallisto/{unit.sample}-{unit.unit}", unit = units[["sample", "unit"]].itertuples()),
        #rRNAdatabases
        expand("resources/rRNA_ref/{ref_db}.fastq", ref_db = config["refs"]["rRNA_ref_dbs"])

        



        