#PBS -W group_list=PROJECT_NAME_HERE -A PROJECT_NAME_HERE
### Job name (comment out the next line to get the name of the script used as the job name)
#PBS -N JOB_NAME_HERE
### Only send mail when job is aborted or terminates abnormally
#PBS -m abe
### Number of nodes
#PBS -l nodes=1:ppn=1
### Memory
#PBS -l mem=4gb
### Requesting time - format is <days>:<hours>:<minutes>:<seconds> (here, 12 hours)
#PBS -l walltime=72:00:00


module load miniconda3/4.12.0
module load mamba-org/mamba/0.24.0
module load snakemake/6.15.3

cd PATH_TO_PIPELINE_DIRECTORY

echo "==================="
echo "Executing Pipeline"
echo "==================="
echo "                   "
echo "Latest Git Commit: "
echo "                   "

git log --name-status HEAD^..HEAD

echo "                    "
echo "===================="
echo " Starting Pipeline  "
echo "===================="



snakemake --profile config/Computerome2 --rerun-incomplete --keep-going
