# snakemake_cluster_config.yaml
executor: 'cluster-generic'

cluster-generic-submit-cmd: "qsub -W group_list=ku_00132 -A ku_00132 -l nodes=1:ppn=8:thinnode,mem=20g,walltime=8:00:00 " 

default-resources: true

# Command to check job status; must return one of: running, completed, failed
#cluster-generic-status-cmd: "pbs-status.py"

# Template jobscript for submitted jobs
#jobscript: "pbs-jobscript.sh"

# Max number of rules to submit from this session (login node)
jobs: 10

# How to name job scripts
jobname: "snakejob.{rule}.{jobid}.sh"

# Snakemake logging verbosity
verbose: true

# Keep temp files
notemp: true

# Wait time (seconds) for NFS / shared filesystem latency
latency-wait: 120

# Conda integration
use-conda: true
conda-prefix: "/home/projects/ku_00132/.conda_cache"

